name: publish develop image 
on:
  push:
    branches:
      - develop

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push develop Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: openimis/openimis-pgsql:develop
